name: Build Stockfish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clone Stockfish
      run: |
        git clone https://github.com/official-stockfish/Stockfish.git
        cd Stockfish/src
        
    - name: Create test output
      run: echo "Сборка Stockfish готова к настройке!" > build-info.txt
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: stockfish-source
        path: Stockfish/
